import type { Metadata } from "next";
import "@blueprintjs/core/lib/css/blueprint.css";
import "react-simple-keyboard/build/css/index.css";
import "./globals.css";

import { PostHogProvider } from "../providers/PostHogProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <PostHogProvider>{children}</PostHogProvider>
      </body>
    </html>
  );
}
